<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <NoWarn>$(NoWarn);NUnit1032;NUnit2021</NoWarn>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Arch" Version="1.2.8" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="NUnit" Version="4.6.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.6.0" />
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Arch.System.SourceGenerator\Arch.System.SourceGenerator.csproj" />
      <ProjectReference Include="..\Arch.System\Arch.System.csproj" />
    </ItemGroup>

</Project>
